export type PermissionDefinition = {
  code: string
  module: string
  action: string
  description: string
}

export type SystemRoleDefinition = {
  code: string
  name: string
  description: string
}

export const PERMISSIONS = [
  {
    code: 'auth.session.read',
    module: 'auth',
    action: 'session.read',
    description: 'View active user sessions',
  },
  {
    code: 'auth.session.revoke',
    module: 'auth',
    action: 'session.revoke',
    description: 'Revoke user sessions',
  },
  {
    code: 'company.read',
    module: 'company',
    action: 'read',
    description: 'View company profile',
  },
  {
    code: 'company.update',
    module: 'company',
    action: 'update',
    description: 'Update company profile',
  },
  {
    code: 'branch.read',
    module: 'branch',
    action: 'read',
    description: 'View branches',
  },
  {
    code: 'branch.create',
    module: 'branch',
    action: 'create',
    description: 'Create branches',
  },
  {
    code: 'branch.update',
    module: 'branch',
    action: 'update',
    description: 'Update branches',
  },
  {
    code: 'branch.delete',
    module: 'branch',
    action: 'delete',
    description: 'Delete branches',
  },
  {
    code: 'warehouse.read',
    module: 'warehouse',
    action: 'read',
    description: 'View warehouses',
  },
  {
    code: 'warehouse.create',
    module: 'warehouse',
    action: 'create',
    description: 'Create warehouses',
  },
  {
    code: 'warehouse.update',
    module: 'warehouse',
    action: 'update',
    description: 'Update warehouses',
  },
  {
    code: 'warehouse.delete',
    module: 'warehouse',
    action: 'delete',
    description: 'Delete warehouses',
  },
  {
    code: 'customer.read',
    module: 'customer',
    action: 'read',
    description: 'View customers',
  },
  {
    code: 'customer.create',
    module: 'customer',
    action: 'create',
    description: 'Create customers',
  },
  {
    code: 'customer.update',
    module: 'customer',
    action: 'update',
    description: 'Update customers',
  },
  {
    code: 'customer.delete',
    module: 'customer',
    action: 'delete',
    description: 'Delete customers',
  },
  {
    code: 'supplier.read',
    module: 'supplier',
    action: 'read',
    description: 'View suppliers',
  },
  {
    code: 'supplier.create',
    module: 'supplier',
    action: 'create',
    description: 'Create suppliers',
  },
  {
    code: 'supplier.update',
    module: 'supplier',
    action: 'update',
    description: 'Update suppliers',
  },
  {
    code: 'supplier.delete',
    module: 'supplier',
    action: 'delete',
    description: 'Delete suppliers',
  },
  {
    code: 'user.read',
    module: 'user',
    action: 'read',
    description: 'View users',
  },
  {
    code: 'user.create',
    module: 'user',
    action: 'create',
    description: 'Create users',
  },
  {
    code: 'user.update',
    module: 'user',
    action: 'update',
    description: 'Update users',
  },
  {
    code: 'user.disable',
    module: 'user',
    action: 'disable',
    description: 'Disable users',
  },
  {
    code: 'role.read',
    module: 'role',
    action: 'read',
    description: 'View roles',
  },
  {
    code: 'role.create',
    module: 'role',
    action: 'create',
    description: 'Create roles',
  },
  {
    code: 'role.update',
    module: 'role',
    action: 'update',
    description: 'Update roles',
  },
  {
    code: 'role.delete',
    module: 'role',
    action: 'delete',
    description: 'Delete roles',
  },
  {
    code: 'role.assign',
    module: 'role',
    action: 'assign',
    description: 'Assign roles to users',
  },
  {
    code: 'permission.read',
    module: 'permission',
    action: 'read',
    description: 'View permission catalog',
  },
  {
    code: 'audit.read',
    module: 'audit',
    action: 'read',
    description: 'View audit logs',
  },
  {
    code: 'document-sequence.read',
    module: 'document-sequence',
    action: 'read',
    description: 'View document numbering rules',
  },
  {
    code: 'document-sequence.create',
    module: 'document-sequence',
    action: 'create',
    description: 'Create document numbering rules',
  },
  {
    code: 'document-sequence.update',
    module: 'document-sequence',
    action: 'update',
    description: 'Update document numbering rules',
  },
  {
    code: 'document-sequence.delete',
    module: 'document-sequence',
    action: 'delete',
    description: 'Disable document numbering rules',
  },
  {
    code: 'document-sequence.generate',
    module: 'document-sequence',
    action: 'generate',
    description: 'Generate document numbers',
  },
  {
    code: 'sales.order.read',
    module: 'sales',
    action: 'order.read',
    description: 'View sales orders',
  },
  {
    code: 'sales.order.create',
    module: 'sales',
    action: 'order.create',
    description: 'Create sales orders',
  },
  {
    code: 'sales.order.update',
    module: 'sales',
    action: 'order.update',
    description: 'Update sales orders',
  },
  {
    code: 'sales.order.approve',
    module: 'sales',
    action: 'order.approve',
    description: 'Approve sales orders',
  },
  {
    code: 'sales.order.cancel',
    module: 'sales',
    action: 'order.cancel',
    description: 'Cancel sales orders',
  },
  {
    code: 'purchase.order.read',
    module: 'purchase',
    action: 'order.read',
    description: 'View purchase orders',
  },
  {
    code: 'purchase.order.create',
    module: 'purchase',
    action: 'order.create',
    description: 'Create purchase orders',
  },
  {
    code: 'purchase.order.update',
    module: 'purchase',
    action: 'order.update',
    description: 'Update purchase orders',
  },
  {
    code: 'purchase.order.approve',
    module: 'purchase',
    action: 'order.approve',
    description: 'Approve purchase orders',
  },
  {
    code: 'purchase.order.cancel',
    module: 'purchase',
    action: 'order.cancel',
    description: 'Cancel purchase orders',
  },
  {
    code: 'inventory.item.read',
    module: 'inventory',
    action: 'item.read',
    description: 'View inventory items',
  },
  {
    code: 'inventory.item.create',
    module: 'inventory',
    action: 'item.create',
    description: 'Create inventory items',
  },
  {
    code: 'inventory.item.update',
    module: 'inventory',
    action: 'item.update',
    description: 'Update inventory items',
  },
  {
    code: 'inventory.item.delete',
    module: 'inventory',
    action: 'item.delete',
    description: 'Delete inventory items',
  },
  {
    code: 'inventory.stock.read',
    module: 'inventory',
    action: 'stock.read',
    description: 'View stock balances',
  },
  {
    code: 'inventory.stock.adjust',
    module: 'inventory',
    action: 'stock.adjust',
    description: 'Adjust stock balances',
  },
  {
    code: 'inventory.stock.transfer',
    module: 'inventory',
    action: 'stock.transfer',
    description: 'Transfer stock between warehouses',
  },
  {
    code: 'finance.invoice.read',
    module: 'finance',
    action: 'invoice.read',
    description: 'View invoices',
  },
  {
    code: 'finance.invoice.create',
    module: 'finance',
    action: 'invoice.create',
    description: 'Create invoices',
  },
  {
    code: 'finance.invoice.update',
    module: 'finance',
    action: 'invoice.update',
    description: 'Update invoices',
  },
  {
    code: 'finance.invoice.post',
    module: 'finance',
    action: 'invoice.post',
    description: 'Post invoices',
  },
  {
    code: 'finance.invoice.cancel',
    module: 'finance',
    action: 'invoice.cancel',
    description: 'Cancel invoices',
  },
  {
    code: 'finance.payment.read',
    module: 'finance',
    action: 'payment.read',
    description: 'View payments',
  },
  {
    code: 'finance.payment.create',
    module: 'finance',
    action: 'payment.create',
    description: 'Create payments',
  },
  {
    code: 'finance.payment.post',
    module: 'finance',
    action: 'payment.post',
    description: 'Post payments',
  },
  {
    code: 'finance.payment.cancel',
    module: 'finance',
    action: 'payment.cancel',
    description: 'Cancel payments',
  },
  {
    code: 'accounting.journal.read',
    module: 'accounting',
    action: 'journal.read',
    description: 'View journal entries',
  },
  {
    code: 'accounting.journal.create',
    module: 'accounting',
    action: 'journal.create',
    description: 'Create journal entries',
  },
  {
    code: 'accounting.journal.post',
    module: 'accounting',
    action: 'journal.post',
    description: 'Post journal entries',
  },
  {
    code: 'accounting.journal.cancel',
    module: 'accounting',
    action: 'journal.cancel',
    description: 'Cancel journal entries',
  },
  {
    code: 'report.read',
    module: 'report',
    action: 'read',
    description: 'View reports',
  },
  {
    code: 'report.export',
    module: 'report',
    action: 'export',
    description: 'Export reports',
  },
  {
    code: 'attachment.read',
    module: 'attachment',
    action: 'read',
    description: 'View attachments',
  },
  {
    code: 'attachment.create',
    module: 'attachment',
    action: 'create',
    description: 'Upload attachments',
  },
  {
    code: 'attachment.delete',
    module: 'attachment',
    action: 'delete',
    description: 'Delete attachments',
  },
] satisfies PermissionDefinition[]

export const SYSTEM_ROLES = [
  {
    code: 'SUPER_ADMIN',
    name: 'Super Admin',
    description: 'Full platform access across all companies',
  },
  {
    code: 'OWNER',
    name: 'Owner',
    description: 'Full company ownership access',
  },
  {
    code: 'ADMIN',
    name: 'Admin',
    description: 'Company administration and operational setup',
  },
  {
    code: 'FINANCE',
    name: 'Finance',
    description: 'Finance, invoice, payment, accounting, and reporting access',
  },
  {
    code: 'SALES',
    name: 'Sales',
    description: 'Sales order and customer-facing transaction access',
  },
  {
    code: 'PURCHASING',
    name: 'Purchasing',
    description: 'Purchase order and supplier-facing transaction access',
  },
  {
    code: 'WAREHOUSE',
    name: 'Warehouse',
    description: 'Inventory item, warehouse, and stock movement access',
  },
  {
    code: 'CASHIER',
    name: 'Cashier',
    description: 'Invoice and payment collection access',
  },
  {
    code: 'AUDITOR',
    name: 'Auditor',
    description: 'Read-only audit and reporting access',
  },
] satisfies SystemRoleDefinition[]

const ALL_PERMISSION_CODES = PERMISSIONS.map((permission) => permission.code)
const READ_PERMISSION_CODES = PERMISSIONS.filter(
  (permission) => permission.action === 'read' || permission.action.endsWith('.read'),
).map((permission) => permission.code)

export const SYSTEM_ROLE_PERMISSIONS: Record<string, string[]> = {
  SUPER_ADMIN: ALL_PERMISSION_CODES,
  OWNER: ALL_PERMISSION_CODES,
  ADMIN: [
    'auth.session.read',
    'auth.session.revoke',
    'company.read',
    'company.update',
    'branch.read',
    'branch.create',
    'branch.update',
    'branch.delete',
    'warehouse.read',
    'warehouse.create',
    'warehouse.update',
    'warehouse.delete',
    'customer.read',
    'customer.create',
    'customer.update',
    'customer.delete',
    'supplier.read',
    'supplier.create',
    'supplier.update',
    'supplier.delete',
    'user.read',
    'user.create',
    'user.update',
    'user.disable',
    'role.read',
    'role.create',
    'role.update',
    'role.assign',
    'permission.read',
    'audit.read',
    'document-sequence.read',
    'document-sequence.create',
    'document-sequence.update',
    'document-sequence.delete',
    'document-sequence.generate',
    'report.read',
    'report.export',
    'attachment.read',
    'attachment.create',
    'attachment.delete',
  ],
  FINANCE: [
    'company.read',
    'branch.read',
    'warehouse.read',
    'customer.read',
    'supplier.read',
    'sales.order.read',
    'purchase.order.read',
    'document-sequence.read',
    'document-sequence.generate',
    'inventory.stock.read',
    'finance.invoice.read',
    'finance.invoice.create',
    'finance.invoice.update',
    'finance.invoice.post',
    'finance.invoice.cancel',
    'finance.payment.read',
    'finance.payment.create',
    'finance.payment.post',
    'finance.payment.cancel',
    'accounting.journal.read',
    'accounting.journal.create',
    'accounting.journal.post',
    'accounting.journal.cancel',
    'report.read',
    'report.export',
    'attachment.read',
    'attachment.create',
  ],
  SALES: [
    'company.read',
    'branch.read',
    'warehouse.read',
    'customer.read',
    'customer.create',
    'customer.update',
    'sales.order.read',
    'sales.order.create',
    'sales.order.update',
    'sales.order.cancel',
    'document-sequence.generate',
    'inventory.item.read',
    'inventory.stock.read',
    'finance.invoice.read',
    'finance.payment.read',
    'report.read',
    'attachment.read',
    'attachment.create',
  ],
  PURCHASING: [
    'company.read',
    'branch.read',
    'warehouse.read',
    'supplier.read',
    'supplier.create',
    'supplier.update',
    'purchase.order.read',
    'purchase.order.create',
    'purchase.order.update',
    'purchase.order.cancel',
    'document-sequence.generate',
    'inventory.item.read',
    'inventory.stock.read',
    'finance.invoice.read',
    'finance.payment.read',
    'report.read',
    'attachment.read',
    'attachment.create',
  ],
  WAREHOUSE: [
    'company.read',
    'branch.read',
    'warehouse.read',
    'inventory.item.read',
    'inventory.item.create',
    'inventory.item.update',
    'inventory.stock.read',
    'inventory.stock.adjust',
    'inventory.stock.transfer',
    'document-sequence.generate',
    'sales.order.read',
    'purchase.order.read',
    'report.read',
    'attachment.read',
    'attachment.create',
  ],
  CASHIER: [
    'company.read',
    'branch.read',
    'customer.read',
    'supplier.read',
    'sales.order.read',
    'finance.invoice.read',
    'finance.payment.read',
    'finance.payment.create',
    'finance.payment.post',
    'document-sequence.generate',
    'report.read',
    'attachment.read',
    'attachment.create',
  ],
  AUDITOR: [...READ_PERMISSION_CODES, 'audit.read', 'report.export', 'attachment.read'],
}
